spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.167.44:5432/hackatona
    username: mobilab
    password: mobilab
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

app-config:
  oauth-clients:
    b2vn-auth-api:
      client: b2vn-auth-api-client
      secret: b2vn-auth-api-secret
    b2vn-radar-api:
      client: b2vn-radar-api-client
      secret: b2vn-radar-api-secret

  services:
    b2vn-auth-api:
#      url: http://auth:8080
      url: http://localhost:8080
    b2vn-radar-api:
#      url: http://radar:8081
      url: http://localhost:8081

security:
  oauth2:
    resource:
      filter-order: 3

server:
  port: 8081

